### PR TITLE
feat: add topic kms key name variable

### PR DESCRIPTION
**Pull request by AndolsiZied**

### CODE REVIEW

**Comment by AndolsiZied** [comment]
Hello @aaron-lane,
Is there a point missing?

**Comment by AndolsiZied** [comment]
Hi @bharathkkb,
To fix checkov violation [CKV_GCP_83](https://github.com/bridgecrewio/checkov/tree/master/checkov/terraform/checks/resource/gcp/CloudPubSubEncryptedWithCMK.py) (Ensure GCP Pub/Sub Topics are encrypted with Customer Supplied Encryption Keys (CSEK)), we have to pass a custom kms. In the current state the module does not take this as a variable. For this I created this PR to pass the KMS as a variable. Exactly like this [PR](https://github.com/terraform-google-modules/terraform-google-scheduled-function/pull/73)

**Review by g-awmalik — APPROVED** [review]

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
