### PR TITLE
feat(TPG >=4.23)!: Add function_docker_registry variables and use them in terraform-google-event-function module

### PR DESCRIPTION
**Pull request by alexrohv**
Update of #120. 

Variables added:

* function_docker_registry
* function_docker_repository
* function_kms_key_name

### CODE REVIEW

**Comment by alexrohv** [comment]
@apeabody

**Comment by alexrohv** [comment]
@apeabody This got out of date. Updated branch.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @alexrohv!

**Pull request merged**
